name: wheater_app
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  # libraries add here -->
  go_router: ^12.1.3 # * routing
  dio: ^5.4.0 # * api consume
  retrofit: '>=4.0.0 <5.0.0' # * api consume
  shared_preferences: ^2.2.2 # session manager
  json_annotation: ^4.8.1 # * json annotation
  animate_do: ^3.0.2  # * animation

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  # libraries add here -->
  retrofit_generator: '>=5.0.0 <6.0.0' # * generator code from api
  build_runner: ^2.4.7  # * generator code
  json_serializable: ^6.7.1  # * generator code

flutter:

  uses-material-design: true

  assets:
    - assets/
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700